### ISSUE TITLE
`yarn add mx-puppet-bridge` fails until my package contains a "build" script

### ISSUE THREAD

**Issue by bridgetheworld** [Sorunome/mx-puppet-bridge#32]
When I was just starting out with my project, I run:

```
yarn add mx-puppet-bridge
```

and got this error:

```
$ yarn add mx-puppet-bridge
yarn add v1.22.4
warning package.json: License should be a valid SPDX license expression
info No lockfile found.
warning mx-puppet-fetlife@0.0.1: License should be a valid SPDX license expression
[1/4] Resolving packages...
warning mx-puppet-bridge > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning mx-puppet-bridge > pg-promise@8.7.5: This version of pg-promise is obsolete. You should update to a newer version.
warning mx-puppet-bridge > matrix-bot-sdk > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] Fetching packages...
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > better-docs@1.4.6" has unmet peer dependency "react@^0.16.0".
warning " > better-docs@1.4.6" has unmet peer dependency "react-dom@^0.16.0".
warning "better-docs > react-ace@6.6.0" has unmet peer dependency "react@^0.13.0 || ^0.14.0 || ^15.0.1 || ^16.0.0".
warning "better-docs > react-ace@6.6.0" has unmet peer dependency "react-dom@^0.13.0 || ^0.14.0 || ^15.0.1 || ^16.0.0".
warning "better-docs > react-frame-component@4.1.1" has unmet peer dependency "prop-types@^15.5.9".
warning "better-docs > react-frame-component@4.1.1" has unmet peer dependency "react@>= 16.3".
warning "better-docs > react-frame-component@4.1.1" has unmet peer dependency "react-dom@>= 16.3".
[5/5] Building fresh packages...
node scripts/try_build.js
No build output found - attempting build
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-04-05T15_52_18_559Z-debug.log
child_process.js:669
    throw err;
    ^

Error: Command failed: npm run build
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.<anonymous> (/home/user/.cache/yarn/v6/.tmp/1572d81cfd533a18b6329a08ac2d22fb.8259b9e470469b243666f420e6cf972758694bbb.prepare/scripts/try_build.js:11:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 125548,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
```

I then added the following to my package.json:

```
  "scripts": {
    "build": "ls"
  },
```

and the build worked fine. Should it be required to have a `build` script to install mx-puppet-bridge?

**Comment by Sorunome** [comment]
does it work with npm?

Am 5. April 2020 17:57:35 MESZ schrieb bridgetheworld <notifications@github.com>:

**Comment by Sorunome** [comment]
Also, there is already a build script defined https://github.com/Sorunome/mx-puppet-bridge/blob/master/package.json#L16 when distributing via npmjs the compiled javascript files are already distributed, though, so it shouldn't be needed to build at all

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/mx-puppet-bridge/commit/9fac04b1d8defb8a0b46bc9dbbccae7617fa3ca9
