### ISSUE TITLE
Error occured while running a puppet instance

### ISSUE THREAD

**Issue by goodspeed34** [Sorunome/mx-puppet-bridge#93]
# Version
typescript@4.4.3
node v16.5.0

# Error Info
Oct-1 08:56:25.940 [PuppetBridge] error: Unhandled Promise Rejection: TypeError: Cannot read property 'registerAppserviceEvents' of undefined
    at PuppetBridge.<anonymous> (/home/nios34/FS/matrix-puppet-oicq-rc/node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:298:37)
    at Generator.next (<anonymous>)
    at /home/nios34/FS/matrix-puppet-oicq-rc/node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/home/nios34/FS/matrix-puppet-oicq-rc/node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:16:12)
    at PuppetBridge.start (/home/nios34/FS/matrix-puppet-oicq-rc/node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:288:16)
    at /home/nios34/FS/matrix-puppet-oicq-rc/out/index.js:164:49
    at step (/home/nios34/FS/matrix-puppet-oicq-rc/out/index.js:33:23)
    at Object.next (/home/nios34/FS/matrix-puppet-oicq-rc/out/index.js:14:53)
    at fulfilled (/home/nios34/FS/matrix-puppet-oicq-rc/out/index.js:5:58)
Oct-1 08:56:25.940 [PuppetBridge] error: Promise {
  <rejected> TypeError: Cannot read property 'registerAppserviceEvents' of undefined
      at PuppetBridge.<anonymous> (/home/nios34/FS/matrix-puppet-oicq-rc/node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:298:37)
      at Generator.next (<anonymous>)
      at /home/nios34/FS/matrix-puppet-oicq-rc/node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:20:71
      at new Promise (<anonymous>)
      at __awaiter (/home/nios34/FS/matrix-puppet-oicq-rc/node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:16:12)
      at PuppetBridge.start (/home/nios34/FS/matrix-puppet-oicq-rc/node_modules/mx-puppet-bridge/lib/src/puppetbridge.js:288:16)
      at /home/nios34/FS/matrix-puppet-oicq-rc/out/index.js:164:49
      at step (/home/nios34/FS/matrix-puppet-oicq-rc/out/index.js:33:23)
      at Object.next (/home/nios34/FS/matrix-puppet-oicq-rc/out/index.js:14:53)
      at fulfilled (/home/nios34/FS/matrix-puppet-oicq-rc/out/index.js:5:58)
}

# Deps
├─ mx-puppet-bridge@0.1.6
│  ├─ @sorunome/matrix-bot-sdk@^0.5.13
│  ├─ better-sqlite3@^7.4.1
│  ├─ blurhash@^1.1.3
│  ├─ canvas@^2.6.1
│  ├─ escape-html@^1.0.3
│  ├─ events@^3.1.0
│  ├─ expire-set@^1.0.0
│  ├─ file-type@^12.4.2
│  ├─ got@^11.6.0
│  ├─ hasha@^5.2.0
│  ├─ js-yaml@^3.13.1
│  ├─ markdown-it@^9.1.0
│  ├─ pg-promise@^10.5.0
│  ├─ prom-client@^13.0.0
│  ├─ unescape@^1.0.1
│  ├─ uuid@^3.4.0
│  ├─ winston-daily-rotate-file@^3.10.0
│  └─ winston@^3.2.1

**Comment by goodspeed34** [comment]
I forgot using puppet.init :-(
