### ISSUE TITLE
"Failure to update to latest schema. And failed to rollback."

### ISSUE THREAD

**Issue by JokerGermany** [Sorunome/mx-puppet-bridge#99]
My mx puppet bridge is in a loop:
```
Apr 23 18:27:00 nas matrix-mx-puppet-discord\[21027\]: /opt/mx-puppet-discord/node\_modules/mx-puppet-bridge/lib/src/store.js:97
Apr 23 18:27:00 nas matrix-mx-puppet-discord\[21027\]:                         throw Error("Failure to update to latest schema. And failed to rollback.");
Apr 23 18:27:00 nas matrix-mx-puppet-discord\[21027\]:                               ^
Apr 23 18:27:00 nas matrix-mx-puppet-discord\[21027\]: Error: Failure to update to latest schema. And failed to rollback.
Apr 23 18:27:00 nas matrix-mx-puppet-discord\[21027\]:     at Store.\<anonymous> (/opt/mx-puppet-discord/node\_modules/mx-puppet-bridge/lib/src/store.js:97:31)
Apr 23 18:27:00 nas matrix-mx-puppet-discord\[21027\]:     at Generator.throw (\<anonymous>)
Apr 23 18:27:00 nas matrix-mx-puppet-discord\[21027\]:     at rejected (/opt/mx-puppet-discord/node\_modules/mx-puppet-bridge/lib/src/store.js:18:65)
Apr 23 18:27:00 nas matrix-mx-puppet-discord\[21027\]:     at processTicksAndRejections (node:internal/process/task\_queues:96:5)
Apr 23 18:27:01 nas systemd\[1\]: matrix-mx-puppet-discord.service: Main process exited, code=exited, status=1/FAILURE
Apr 23 18:27:01 nas systemd\[1\]: matrix-mx-puppet-discord.service: Failed with result 'exit-code'.
Apr 23 18:27:31 nas systemd\[1\]: matrix-mx-puppet-discord.service: Service hold-off time over, scheduling restart.
Apr 23 18:27:31 nas systemd\[1\]: matrix-mx-puppet-discord.service: Scheduled restart job, restart counter is at 115.
Apr 23 18:27:31 nas systemd\[1\]: Stopped Matrix Mx Puppet Discord bridge.
Apr 23 18:27:31 nas systemd\[1\]: Starting Matrix Mx Puppet Discord bridge...
Apr 23 18:27:37 nas systemd\[1\]: Started Matrix Mx Puppet Discord bridge.
Apr 23 18:27:40 nas matrix-mx-puppet-discord\[22238\]: Apr-23 16:27:40.865 \[Store\] info: Starting DB Init
Apr 23 18:27:40 nas matrix-mx-puppet-discord\[22238\]: Apr-23 16:27:40.868 \[Store\] info: connString present in config, using postgres
Apr 23 18:27:40 nas matrix-mx-puppet-discord\[22238\]: Apr-23 16:27:40.869 \[Postgres\] info: Opening @matrix-postgres:5432/matrix\_mx\_puppet\_discord?sslmode=disable
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]: Apr-23 16:27:41.027 \[Store\] info: Database schema version is 12, latest version is 16
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]: Apr-23 16:27:41.062 \[Store\] info: Updating database to v13, "chan\_store --> room\_store, and add more parameters"
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]: Apr-23 16:27:41.070 \[Store\] error: Couldn't update database to schema  13
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]: Apr-23 16:27:41.072 \[Store\] error: Error: Error creating 'room\_store': error: relation "room\_store" already exists
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]:     at Store.\<anonymous> (/opt/mx-puppet-discord/node\_modules/mx-puppet-bridge/lib/src/store.js:158:23)
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]:     at Generator.throw (\<anonymous>)
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]:     at rejected (/opt/mx-puppet-discord/node\_modules/mx-puppet-bridge/lib/src/store.js:18:65)
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]:     at processTicksAndRejections (node:internal/process/task\_queues:96:5)
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]: Apr-23 16:27:41.072 \[Store\] error: Schema migration failed! Please visit #mx-puppet-bridge:sorunome.de and ask for help!
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]: Apr-23 16:27:41.073 \[Store\] info: Rolling back to version  12
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]: Apr-23 16:27:41.074 \[Store\] error: Error: Error creating 'chan\_store': error: relation "chan\_store" already exists
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]:     at Store.\<anonymous> (/opt/mx-puppet-discord/node\_modules/mx-puppet-bridge/lib/src/store.js:158:23)
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]:     at Generator.throw (\<anonymous>)
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]:     at rejected (/opt/mx-puppet-discord/node\_modules/mx-puppet-bridge/lib/src/store.js:18:65)
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]:     at processTicksAndRejections (node:internal/process/task\_queues:96:5)
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]: /opt/mx-puppet-discord/node\_modules/mx-puppet-bridge/lib/src/store.js:97
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]:                         throw Error("Failure to update to latest schema. And failed to rollback.");
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]:                               ^
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]: Error: Failure to update to latest schema. And failed to rollback.
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]:     at Store.\<anonymous> (/opt/mx-puppet-discord/node\_modules/mx-puppet-bridge/lib/src/store.js:97:31)
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]:     at Generator.throw (\<anonymous>)
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]:     at rejected (/opt/mx-puppet-discord/node\_modules/mx-puppet-bridge/lib/src/store.js:18:65)
Apr 23 18:27:41 nas matrix-mx-puppet-discord\[22238\]:     at processTicksAndRejections (node:internal/process/task\_queues:96:5)
Apr 23 18:27:42 nas systemd\[1\]: matrix-mx-puppet-discord.service: Main process exited, code=exited, status=1/FAILURE
Apr 23 18:27:42 nas systemd\[1\]: matrix-mx-puppet-discord.service: Failed with result 'exit-code'.
Apr 23 18:28:12 nas systemd\[1\]: matrix-mx-puppet-discord.service: Service hold-off time over, scheduling restart.
Apr 23 18:28:12 nas systemd\[1\]: matrix-mx-puppet-discord.service: Scheduled restart job, restart counter is at 116.
Apr 23 18:28:12 nas systemd\[1\]: Stopped Matrix Mx Puppet Discord bridge.
Apr 23 18:28:12 nas systemd\[1\]: Starting Matrix Mx Puppet Discord bridge...

```

**Comment by JokerGermany** [comment]
could be because device space was full, but i started fresh
